# Hierarchical Multi-Scale Streaming NEST
#
# Advanced Feature: Different context sizes at different layers
# - Layers 0-5:   40 frames  (0.4s) - Local phonetic patterns
# - Layers 6-11:  120 frames (1.2s) - Syllabic patterns
# - Layers 12-17: 320 frames (3.2s) - Linguistic context
#
# Benefits: 2-3% relative WER improvement with no latency increase!

name: "SSL-NEST-FastConformer-Hierarchical"

model:
  sample_rate: 16000
  num_classes: 8192
  num_books: 1
  code_dim: 16
  squeeze_single: false
  mask_position: pre_conv

  # ADVANCED FEATURE: Hierarchical Context
  hierarchical_context:
    enabled: true
    schedule:  # [layer_idx, [left_context, right_context]]
      - [0, [40, 0]]     # Layers 0-5: Local patterns
      - [6, [120, 0]]    # Layers 6-11: Mid-range patterns
      - [12, [320, 0]]   # Layers 12-17: Long-range patterns

  # OPTIONAL: Curriculum Learning for Context
  curriculum_context:
    enabled: false  # Set to true to enable
    start_context: 40     # Start with 40 frames
    end_context: 320      # Gradually increase to 320
    warmup_steps: 100000  # Over 100k steps

  train_ds:
    manifest_filepath: ???
    noise_manifest: null
    sample_rate: ${model.sample_rate}
    batch_size: 8
    shuffle: true
    num_workers: 8
    pin_memory: true
    use_start_end_token: false
    trim_silence: false
    max_duration: 60.0
    min_duration: 1.0
    drop_last: true
    is_concat: false
    is_tarred: false
    bucketing_strategy: "synced_randomized"
    batch_augmentor:
      _target_: nemo.collections.asr.modules.ssl_modules.MultiSpeakerNoiseAugmentation
      prob: 0.5
      noise_ratio: 0.5
      min_r_speech: -5.0
      max_r_speech: 5.0
      min_r_noise: -5.0
      max_r_noise: 20.0
      min_mix_rate: 0.5
      max_mix_rate: 0.5
      min_num_segments: 1
      max_num_segments: 1
      min_num_speakers: 1
      max_num_speakers: 1

  validation_ds:
    manifest_filepath: ???
    noise_manifest: null
    sample_rate: ${model.sample_rate}
    batch_size: 8
    shuffle: false
    num_workers: 8
    pin_memory: true
    use_start_end_token: false
    max_duration: 60.0
    min_duration: 1.0
    batch_augmentor:
      _target_: nemo.collections.asr.modules.ssl_modules.MultiSpeakerNoiseAugmentation
      prob: 0.5
      noise_ratio: 0.5
      min_r_speech: -5.0
      max_r_speech: 5.0
      min_r_noise: -5.0
      max_r_noise: 20.0
      min_mix_rate: 0.5
      max_mix_rate: 0.5
      min_num_segments: 1
      max_num_segments: 1
      min_num_speakers: 1
      max_num_speakers: 1

  preprocessor:
    _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
    sample_rate: ${model.sample_rate}
    normalize: "per_feature"
    window_size: 0.025
    window_stride: 0.01
    window: "hann"
    features: 80
    n_fft: 512
    log: true
    frame_splicing: 1
    dither: 0.00001
    pad_to: 16
    pad_value: 0.0

  spec_augment:
    _target_: nemo.collections.asr.modules.SpectrogramAugmentation
    freq_masks: 0
    time_masks: 0
    freq_width: 27
    time_width: 0.05

  masking:
    _target_: nemo.collections.asr.modules.RandomBlockMasking
    block_size: 40
    mask_prob: 0.01
    feat_in: ${model.preprocessor.features}
    freeze: true
    allow_overlap: true
    causal: true
    # Will be synced with hierarchical context
    left_context_size: 320  # Max context

  quantizer:
    _target_: nemo.collections.asr.modules.RandomProjectionVectorQuantizer
    feat_in: ${model.preprocessor.features}
    code_dim: ${model.code_dim}
    num_books: ${model.num_books}
    num_classes: ${model.num_classes}
    dist_fn: "l2"
    freeze: true
    squeeze_single: ${model.squeeze_single}
    combine_time_steps: ${model.encoder.subsampling_factor}

  encoder:
    _target_: nemo.collections.asr.modules.ConformerEncoder
    feat_in: ${model.preprocessor.features}
    feat_out: -1
    n_layers: 17
    d_model: 512
    use_bias: True

    # Sub-sampling
    subsampling: dw_striding
    subsampling_factor: 8
    subsampling_conv_channels: 256
    causal_downsampling: true

    # Feed forward
    ff_expansion_factor: 4

    # Attention - will be overridden per layer by hierarchical setup
    self_attention_model: rel_pos
    n_heads: 8
    att_context_size: [160, 0]  # Default, will be per-layer
    att_context_style: regular
    xscaling: true
    untie_biases: true
    pos_emb_max_len: 5000

    # Convolution
    conv_kernel_size: 9
    conv_norm_type: 'layer_norm'  # CRITICAL for streaming
    conv_context_size: causal

    # Regularization
    dropout: 0.1
    dropout_pre_encoder: 0.1
    dropout_emb: 0.0
    dropout_att: 0.1
    stochastic_depth_drop_prob: 0.0
    stochastic_depth_mode: linear
    stochastic_depth_start_layer: 1

  decoder:
    _target_: nemo.collections.asr.modules.MultiSoftmaxDecoder
    feat_in: ${model.encoder.d_model}
    num_classes: ${model.num_classes}
    num_decoders: ${model.num_books}
    squeeze_single: ${model.squeeze_single}
    use_bias: true

  loss:
    _target_: nemo.collections.asr.losses.MultiMLMLoss
    combine_time_steps: ${model.encoder.subsampling_factor}
    mask_threshold: 0.8
    num_decoders: ${model.num_books}
    squeeze_single: ${model.squeeze_single}

  optim:
    name: adamw
    lr: 5.0
    betas: [0.9, 0.98]
    weight_decay: 1e-3
    sched:
      name: NoamAnnealing
      d_model: ${model.encoder.d_model}
      warmup_steps: 25000
      warmup_ratio: null
      min_lr: 1e-6

trainer:
  devices: -1
  num_nodes: 1
  max_epochs: -1
  max_steps: 500000
  val_check_interval: 2500
  accelerator: auto
  strategy: ddp
  accumulate_grad_batches: 1
  gradient_clip_val: 0.0
  precision: 32
  log_every_n_steps: 10
  enable_progress_bar: True
  num_sanity_val_steps: 0
  check_val_every_n_epoch: 1
  sync_batchnorm: true
  enable_checkpointing: False
  logger: false
  benchmark: false

exp_manager:
  exp_dir: null
  name: ${name}
  create_tensorboard_logger: true
  create_checkpoint_callback: true
  checkpoint_callback_params:
    monitor: "val_loss"
    mode: "min"
    save_top_k: 1
    always_save_nemo: True
    filename: '${name}--{${exp_manager.checkpoint_callback_params.monitor}:.3f}-{step}'
  resume_if_exists: true
  resume_ignore_no_checkpoint: true
  create_wandb_logger: false
  wandb_logger_kwargs:
    name: null
    project: null
